---
stages:
  - gen_version
  - test
  - build_docker_image_testing

gen_version:
  stage: gen_version
  interruptible: false
  image: "harbor.vanillastack.io/vanillastack/vanilla-ubuntu-base:20201211"
  script:
    - echo "VERSION=$(date +'%Y%m')-$CI_COMMIT_SHORT_SHA" > vars.env
    - cat vars.env
  artifacts:
    reports:
      dotenv: vars.env    

build_docker_image_testing:
  only:
    refs:
      - testing
  stage: build_docker_image_testing
  interruptible: true
  allow_failure: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"harbor.cloudical.net/vanillastack\":{\"auth\":\"$(echo -n "robot$build-backend-gitlab.cloudical.net":$HARBOR_ROBOT_KEY_BUILD_BACKEND | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg VERSION=$VERSION --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/prod/installer/alpine/Dockerfile --destination harbor.cloudical.net/vanillastack/installer:testing-latest --destination harbor.cloudical.net/vanillastack/installer:testing-$VERSION 

include:
  # - local: "/live_image/.gitlab-ci.yaml"
  - template: Security/SAST.gitlab-ci.yml
