---
image: "harbor.vanillastack.io/vanillastack/vanilla-ubuntu-base:20201211"
services:
  - docker:18.09.7-dind
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://localhost:2375
  SAST_EXCLUDED_PATHS: "docs"
  SECRET_DETECTION_EXCLUDED_PATHS: "docs"
  SEARCH_MAX_DEPTH: 50

stages:
  - gen_version
  - test
  - build_docker_image_dev
  - build_docker_image_testing
  - build_docker_image_prod
  - build_liveimage
  - release

gen_version:
  stage: gen_version
  interruptible: false
  script:
    - echo "VERSION=$(date +'%Y%m')-$CI_COMMIT_SHORT_SHA" > vars.env
    - cat vars.env
  artifacts:
    reports:
      dotenv: vars.env

build_docker_image_dev:
  only:
    refs:
      - backend_testing
  stage: build_docker_image_dev
  interruptible: true
  script:
    - docker login -u 'robot$build-backend-gitlab.cloudical.net' -p "$HARBOR_ROBOT_KEY_BUILD_BACKEND" harbor.cloudical.net/vanillastack
    - echo "$VERSION" > version
    - docker build -f docker/prod/installer/alpine/Dockerfile -t harbor.cloudical.net/vanillastack/installer:dev-$VERSION -t harbor.cloudical.net/vanillastack/installer:dev-latest .
    - docker push harbor.cloudical.net/vanillastack/installer:dev-$VERSION
    - docker push harbor.cloudical.net/vanillastack/installer:dev-latest

build_docker_image_testing:
  only:
    refs:
      - testing
  stage: build_docker_image_testing
  interruptible: true
  allow_failure: true
  script:
    - docker login -u 'robot$build-backend-gitlab.cloudical.net' -p "$HARBOR_ROBOT_KEY_BUILD_BACKEND" harbor.cloudical.net/vanillastack
    - echo "VERSION" > version
    - docker build -f docker/prod/installer/alpine/Dockerfile -t harbor.cloudical.net/vanillastack/installer:testing-$VERSION -t harbor.cloudical.net/vanillastack/installer:testing-latest .
    - docker push harbor.cloudical.net/vanillastack/installer:testing-$VERSION
    - docker push harbor.cloudical.net/vanillastack/installer:testing-latest

build_docker_image_prod:
  only:
    refs:
      - master
  stage: build_docker_image_prod
  interruptible: false
  script:
    - docker login -u 'robot$build-backend-gitlab.cloudical.net' -p "$HARBOR_ROBOT_KEY_BUILD_BACKEND" harbor.cloudical.net/vanillastack
    - echo "VERSION" > version
    - docker build -f docker/prod/installer/alpine/Dockerfile -t harbor.cloudical.net/vanillastack/installer:$VERSION -t harbor.cloudical.net/vanillastack/installer:latest .
    - docker push harbor.cloudical.net/vanillastack/installer:$VERSION
    - docker push harbor.cloudical.net/vanillastack/installer:latest

release:
  only:
    refs:
      - master
  stage: release
  interruptible: false
  release:
    tag_name: "$VERSION"
    description: "VanillaStack stable release $VERSION"
  script:
    - echo "Publish release $VERSION"
  image: registry.gitlab.com/gitlab-org/release-cli

include:
  - local: "/live_image/.gitlab-ci.yaml"
  - template: Security/SAST.gitlab-ci.yml
#  - template: Security/Secret-Detection.gitlab-ci.yml
