build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context . --dockerfile ./docker/prod/installer/alpine/Dockerfile --no-push
