---
stages:
  - gen_version
  - test
  - build_docker_image_testing
  - push_docker_image_testing
  - build_docker_image_prod
  - release_job
  - release
  - push_docker_image_prod
  # - build_liveimage
  # - build_liveimage_prod

gen_version:
  stage: gen_version
  interruptible: false
  image: "harbor.vanillastack.io/vanillastack/vanilla-ubuntu-base:20201211"
  script:
    - echo "VERSION=$(date +'%Y%m')-$CI_COMMIT_SHORT_SHA" > vars.env
    - cat vars.env
  artifacts:
    reports:
      dotenv: vars.env    

build_docker_image_testing:
  only:
    refs:
      - testing
  stage: build_docker_image_testing
  interruptible: true
  allow_failure: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/prod/installer/alpine/Dockerfile --no-push --cache

push_docker_image_testing:
  only:
    refs:
      - testing
  stage: push_docker_image_testing
  interruptible: true
  allow_failure: true
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"harbor.cloudical.net\":{\"auth\":\"$(printf "%s:%s" "robot\$build-backend-gitlab.cloudical.net" "${HARBOR_ROBOT_KEY_BUILD_BACKEND}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --build-arg VERSION=$VERSION --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/prod/installer/alpine/Dockerfile --destination harbor.cloudical.net/vanillastack/installer:testing-$VERSION --destination harbor.cloudical.net/vanillastack/installer:testing-latest

build_docker_image_prod:
  only:
    refs:
      - master
  stage: build_docker_image_prod
  interruptible: false
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/prod/installer/alpine/Dockerfile --no-push --cache

release_job:
  only:
    refs:
      - master
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'

push_docker_image_prod:
only:
  refs:
    - master
stage: push_docker_image_prod
interruptible: false
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
script:
  - echo "{\"auths\":{\"harbor.cloudical.net\":{\"auth\":\"$(printf "%s:%s" "robot\$build-backend-gitlab.cloudical.net" "${HARBOR_ROBOT_KEY_BUILD_BACKEND}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --build-arg RELEASE=$CI_COMMIT_TAG --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docker/prod/installer/alpine/Dockerfile --destination harbor.cloudical.net/vanillastack/installer:$RELEASE --destination harbor.cloudical.net/vanillastack/installer:latest --cleanup

include:
  - template: Security/SAST.gitlab-ci.yml
  # - local: "/live_image/.gitlab-ci.yaml"
