---
- name: Test Playbook
  hosts: "{{host}}"
  gather_facts: false
  become: false
  tasks:
    - name: Counter
      shell: "echo {{ index }}"
      with_sequence: count='1'
      loop_control:
        pause: 5
        extended: yes
        index_var: index
